name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.23.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo run lint check
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node-version: [14]
        os: [ubuntu-latest, macOS-latest, windows-2019]
        include:
          - node-version: 16
            os: ubuntu-latest
    env:
      TURBO_CACHE_KEY: ${{ matrix.os }}-${{ matrix.node-version }}
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.23.2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Get paths for OS
        uses: ./.github/actions/env
        id: paths
      - name: Cache browsers
        id: browser_cache
        uses: actions/cache@main
        with:
          path: ${{ steps.paths.outputs.browser_cache_path }}
          key: chromium-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ steps.browser_cache.outputs.cache-hit == 'true' }}
      - run: pnpm turbo run test
      - name: archive test results
        if: failure()
        shell: bash
        run: find packages -type d -name test-results -not -empty | tar -czf test-results.tar.gz --exclude='*-retry*' --files-from=-
      - name: Upload failed tests screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          retention-days: 3
          name: test-failure-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.node-version }}
          path: test-results.tar.gz
